### ISSUE TITLE
MPV freezes

### ISSUE THREAD

**Issue by tyusha0** [cizia64/CrossMix-OS#102]
MPV freezes after some time of watching the video. This is best and faster seen on online streams like this https://hls.goodgame.ru/hls/5346.m3u8 
Create a m3u file 
#EXTM3U
#EXTINF:-1,Akudji
https://hls.goodgame.ru/hls/5346.m3u8
and test on your device

**Comment by cizia64** [comment]
Indeed, no logs, no excessive temperature... 
It also happens with local videos
Could be something related to a bugger overflow...
It will requires some debugging.

**Comment by tyusha0** [comment]
> Indeed, no logs, no excessive temperature...
> It also happens with local videos

Yap, I forgot to write about this.
This bug was already in v1.1.0

**Comment by flgr** [comment]
I think I have a fix for this. See https://discord.com/channels/741895796315914271/1177336131457646722/1253097071087583294

Iirc I have had 0 trouble with (very) large files since I applied those two options.

**Comment by cizia64** [comment]
Well done flgr, this `--terminal=no` makes all the difference ! I add that for the next CrossMix version, thank you.

**Comment by tyusha0** [comment]
> Well done flgr, this `--terminal=no` makes all the difference ! I add that for the next CrossMix version, thank you.

Great, it works: 2 hours of streaming without errors
