### ISSUE TITLE
Widescreen support not working properly on DC and PSX

### ISSUE THREAD

**Issue by thomasbad** [cizia64/CrossMix-OS#115]
For DC:
Widescreen support works, but not full screen by default

For PSX:
Test 10 games, none of them works, will pops up error saying "No BIOS found, swanstation may not work", but simply enter the game with default setting by pressing A to enter is fine and playable

**Comment by GetTuh** [comment]
For PS you need your own bios file in the BIOS folder on SD card. Works flawlessly for me

**Comment by thomasbad** [comment]
> For PS you need your own bios file in the BIOS folder on SD card. Works flawlessly for me

I have tried to place there by create a new sub folder there also since there is no folder names PSX or PS there. What is the path have you placed the PS BIOS?

**Comment by thomasbad** [comment]
Okay, now understand how it works now, need the same structure as Retroarch/.retroarch/system does
