### ISSUE TITLE
Tried PSX Analog Detectir

### ISSUE THREAD

**Issue by rjbulthu** [cizia64/CrossMix-OS#13]
Hey guys! I tried the PSX analog detector and now it’s stuck on a loading screen. Any idea how to fix it? I’ve done multiple reboots. 
![IMG_1398](https://github.com/cizia64/CrossMix-OS/assets/79522011/281e50ca-cd4d-4908-a137-c9465e0797e2)

**Comment by cizia64** [comment]
It could be long if you have many PSX games: Retroarch is scanning the games in backgroup to add them in its database, then the database is compared to the list of games compatible with analog gamepads.
If it stucks for a long time press Menu + Power during 3 seconds to force the exit (it works with any app/emulator in CrossMix).
It could be interesting to enable the logs in RA and check what is happening in your case.

**Comment by cizia64** [comment]
To avoid to resume on an app or on a game, press menu during the boot (until you see 3 bleu flashs).

**Comment by cizia64** [comment]
Have you fixed your problem ?

**Comment by rjbulthu** [comment]
I actually did! I finally got it restarted. Thank you, no issues since.

**Comment by cizia64** [comment]
Other users have the same problem. I have to test that with a high number of games.

**Comment by cizia64** [comment]
Should be fixed in CrossMix v1.2.1.
Feel free to open it again if you have problems.
