### ISSUE TITLE
[Question] Recording from a microphone

### ISSUE THREAD

**Issue by tyusha0** [cizia64/CrossMix-OS#137]
Has anyone tried recording sound from a microphone? My microphone sensitivity is very low.

`LD_LIBRARY_PATH="/mnt/SDCARD/Apps/ScreencapTK/lib:$LD_LIBRARY_PATH" /mnt/SDCARD/Apps/ScreencapTK/bin/ffmpeg -f oss -i /dev/dsp -t 10 mic.mp3`

**Comment by dxdatabase** [comment]
Change the mic gain in alsamixer to 31 (more will saturate). It's set to 0 by default.
