### ISSUE TITLE
Add Syncthing as a system service

### ISSUE THREAD

**Issue by sirchia** [cizia64/CrossMix-OS#14]
First of all: great work on CrossMix so far and thank you for opening up the efforts for use by and contribution from the community!

I'm using Syncthing (https://syncthing.net/) as a service on my home server and my TSP to backup and manage all roms, art, BIOSes saves and settings etc. It's available on many CFW like KNULLI and would love to see it added to CrossMix as well.

I'm currently using https://github.com/veckia9x/Trimui-X/tree/main/Apps/Syncthing as an app on it, but I would prefer to see a better integrated version in System Tools that also starts up the service on reboot.

I also saw your recent addition of telnetd in https://github.com/cizia64/CrossMix-OS/commit/641bba0f1fd22f7a161b6af9183b038f30c950f1 and might take a stab at combining the two.

**Comment by cizia64** [comment]
Good idea ! I put that in the to do list!

**Comment by cizia64** [comment]
Done ! Will be released in CrossMix 1.1.0.
https://github.com/cizia64/CrossMix-OS/commit/78c5ec892e36bd77169dbdb0f8dac66176a5ce32

**Comment by sirchia** [comment]
That’s awesome! Looking forward to the new release!

**Comment by cizia64** [comment]
Released in v1.1.0 today ;)
