### ISSUE TITLE
[Feature] Terminal emulator possibility

### ISSUE THREAD

**Issue by cobaltgit** [cizia64/CrossMix-OS#16]
Was wondering if it would be possible to have some sort of terminal emulator application with an on-screen keyboard. Would be something similar to [Onion's](https://onionui.github.io/docs/apps/terminal) terminal emulator on the Miyoo Mini handhelds in how it's implemented

**Comment by ogregorio** [comment]
I believe any emulator with SDL support can be ported, such as [st-sdl-gameshell](https://github.com/pleft/st-sdl-gameshell). The issue here is the dependency on the X library, which is required to run it. If you find an emulator for the Miyo Mini, I think it will be fully compatible.

**Comment by cobaltgit** [comment]
Yeah so the onion one should work on the smart pro as iirc the screen recorder app originated from onion i think? Will have to test

**Comment by ogregorio** [comment]
Yes, our Onion brothers face problems very similar to ours.

**Comment by cizia64** [comment]
Having a Terminal would be interesting. I know that Schmurtzm is waiting for it to port his Scraper made for Onion on the TSP.

This [Terminal app](https://cdn.discordapp.com/attachments/1177336131457646722/1228461231661252730/Project1.7z?ex=666622ad&is=6664d12d&hm=ccb8742bf0852956f1ed86e2663c86c49dc8e246aa233acd234425cb16019094&) has been made by kiwibonga , there are sources but the already compiled binary doesn't work as it should. 

May be the easiest is to compile the SDL 1 Terminal used in Onion (https://github.com/OnionUI/app-Terminal the controls should be similar, it contains some interesting fixes and little features but may be it will not fit on the resolution ?)

**Comment by cizia64** [comment]
Good news: https://www.reddit.com/r/trimui/comments/1dwhuvm/released_simpleterminal_a_terminal_emulator_for/
