### ISSUE TITLE
Sort favorites function does not work

### ISSUE THREAD

**Issue by mg3600** [cizia64/CrossMix-OS#188]
The option to sort the games on the favorites tab does not work. It seems to do something, because it moves some of the games to the top of the list and some games on the same platform are next to each other, but the result is still a mess.

**Comment by Nevrdid** [comment]
Yup, looks the favourite json is broken. Don't think it's caused by crossmix as the sort script is the only one which reference the favourite file.
You can fix it running this in the terminal :
`sed -i 's/^{.*,"label/{"label/' /mnt/SDCARD/Roms/favourite2.json`

**Comment by Nevrdid** [comment]
Fix here : #189

**Comment by mg3600** [comment]
Thank you very much, your it worked :) I dont know how it messed up, but somehow each line  carried over the sublabels of the previous one.

**Comment by mg3600** [comment]
Thank you very much, your it worked :) I dont know how it messed up, but somehow each line  carried over the sublabels of the previous one.
