### ISSUE TITLE
PortMaster button mapping weirdness if WiFi is turned on

### ISSUE THREAD

**Issue by Larkas** [cizia64/CrossMix-OS#198]
So, I've just installed the latest CrossMix, and I'm getting a pretty weird behavior from PortMaster. I was able to pinpoint what was causing it, but it only made me more confused: if I turn on WiFi, the buttons on PortMaster go nuts, with A being read as B and B automatically exiting the app (thus, behaving somewhat like Start+Select). As a result of this, I simply can't enter any submenu (none of the other buttons are being read as A). If I turn WiFi back off, it goes back to normal (but then I can't update stuff in the app). That doesn't carry over to installed ports - the prepacked Celeste Classic works the same with WiFi turned both on and off, as expected. I have no idea what might be happening!

**Comment by Nevrdid** [comment]
Well yeah that a strange one there x) I don't have this issue tho the only thing which can explain this comming from my mind is an hardware issue x'/ Could you however try with a fresh crossmix installation if you have a spare sdcard to be sure ? ( And maybe reset factory you tsp if it not help)

**Comment by Larkas** [comment]
I don't have a spare card, but I wouldn't mind backing up the one I'm using and formatting it to test stuff up! I'll need a little handholding, though, if you don't mind:
1) I imagine CrossMix writes stuff in the flash memory. Do you think I should uninstall it first? If so, how would I do that? Should I factory reset before or after unistalling it?
2) Should I test some specific version of CrossMix, or should I go with the latest?
Also, an update that might or might not be relevant: I tried using the latest PortMaster in place of the one bundled with CrossMix, with, uh, mixed results. Turning on wifi doesn't mess up with the button mapping, but I can't access the online library - it says I'm in offline mode, even though my IP _is_ shown in the options menu. Talk about random weirdness!

**Comment by Larkas** [comment]
I did a fresh install of the latest version of CrossMix, but didn't factory reset or uninstall anything. It actually worked! Hence, I'm closing this 💪
