### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by Assassins78pl** [cizia64/CrossMix-OS#2]
:)

**Comment by cizia64** [comment]
Hi, 
I suppose that you talk about the theme and the polish language, there's nothing more from you in CrossMix-OS.
I was supposing that these files were offered to everyone as it was published initially published freely in the polish community.
I had credited the known author (S3V3N).
Really sorry about that, I have already removed your assets from the repo :  https://github.com/cizia64/CrossMix-OS/commit/a6fcbd1c311da7e5ba8bfa82756828d12746af01

**Comment by Assassins78pl** [comment]
S3V3N its me.
