### ISSUE TITLE
How about a development branch?

### ISSUE THREAD

**Issue by ogregorio** [cizia64/CrossMix-OS#20]
The project is really cool, but I think it would be interesting to have more branches, a development, and staging branches for example. I saw a really fascinating PR ([19](https://github.com/cizia64/CrossMix-OS/pull/19)) and I want to test, but I think the ideal would be to launch a development release for us to test before merge in main.

**Comment by cobaltgit** [comment]
+1

**Comment by BlackMix** [comment]
yeah, and i saw some lots changes and has PR break.

**Comment by cizia64** [comment]
Hi thank for the advice I keep the point mind.
I could merge the PR into a branch but for now Main is the dev branch and the release the only "ready to use" package.
If I merge it yes it would be in a new branch but I don't plan to merge this PR as is,  you could clone the repo from Kvn0l if you want to make some tests.
Note that the PPSSPP and NDS updates are already in the main branch. For the CPU settings on each emulator we will take a different approach but the work of Kvn0l  will be very useful. 
I think that the first step is to setup a way to collaborate: discussing of what you have in mind before making a PR avoid to work on the same subject and potentially avoid a lot of PR breaks ;)
