### ISSUE TITLE
Missing system icons

### ISSUE THREAD

**Issue by luigira** [cizia64/CrossMix-OS#21]
After changing theme, some system icons are missing, no matter what I change in official settings app or in the system tools app, psp and pico-8 have a blank icon, gamer are there and working but is annoying navigating on an empty space

**Comment by cizia64** [comment]
Hi, which themes are you using ?

In CrossMix you have 3 big way to change the look of the UI : 
- The themes (exactly as in stock), it sets the environment, colors, etc..
- The icons collections in system tools : will impact all the emulators icons
- The Wallpapers collections : will impact the background for each emulator

So if you use the included icons packs it should be OK. 
Note that PICO and PSP have been renamed compared to stock/Tomato (it was PICO8.png and PPSSPP.png before).

**Comment by luigira** [comment]
For now I just return everything to default and still missing icons, I notice they disappear the first time I select XBM icons in system tools. 

The first one suppose to be pico-8 and the second one PSP
![IMG_0153](https://github.com/cizia64/CrossMix-OS/assets/26944543/97ab887b-26ca-4d2a-8ca8-37fa9ff1fe6d)

is a manual way for me to get the icons back?

**Comment by cizia64** [comment]
You have mixed some roms folder from stock OS, in Roms and Emus folder rename PICO8 and PPSSPP   into PICO and PSP then go in system tools and apply an icon collection again.

**Comment by luigira** [comment]
it works! thanks!

**Comment by cizia64** [comment]
Thanks for your feedback, I close ;)
