### ISSUE TITLE
Libz missing in 1.2.1?

### ISSUE THREAD

**Issue by Sirchacha2** [cizia64/CrossMix-OS#215]
Hey I'm trying to run ship of harkinian on the TSP and the log I provided to portmaster was saying that I'm missing  the libz library, is that supposed to be included on crossmix or is it something not solved for yet? Here's the SoH log.

https://pastebin.com/KN1eYWLw

**Comment by pietrondo** [comment]
Same problem:


`root@TinaLinux:/mnt/SDCARD/Data/ports/soh2# cat log.txt
Checking if CFW_NAME 'TrimUI' is in the list...
Comparing 'ArkOS' with 'TrimUI'...
Comparing 'ArkOS wuMMLe' with 'TrimUI'...
Comparing 'ArkOS AeUX' with 'TrimUI'...
Comparing 'knulli' with 'TrimUI'...
Comparing 'TrimUI' with 'TrimUI'...
Match found: 'TrimUI'
Using compatibility binary...
Loading, please wait... (might take a while!)
Running in UINPUT output mode.
./2s2h.elf: /usr/lib/libz.so.1: no version information available (required by /mnt/SDCARD/System/lib/libpng16.so.16)
./2s2h.elf: /usr/lib/libz.so.1: no version information available (required by /mnt/SDCARD/System/lib/libpng16.so.16)
./2s2h.elf: symbol lookup error: /mnt/SDCARD/System/lib/libpng16.so.16: undefined symbol: inflateValidate, version ZLIB_1.2.9
Running in Fake Keyboard mode
Using ConfigFile soh2.gptk
Joystick 0 has game controller name 'Xbox 360 Controller'`

**Comment by pietrondo** [comment]
root@TinaLinux:/mnt/SDCARD/Data/ports/soh2# cat log.txt
Checking if CFW_NAME 'TrimUI' is in the list...
Comparing 'ArkOS' with 'TrimUI'...
Comparing 'ArkOS wuMMLe' with 'TrimUI'...
Comparing 'ArkOS AeUX' with 'TrimUI'...
Comparing 'knulli' with 'TrimUI'...
Comparing 'TrimUI' with 'TrimUI'...
Match found: 'TrimUI'
Using compatibility binary...
Loading, please wait... (might take a while!)
Running in UINPUT output mode.
./2s2h.elf: /usr/lib/libz.so.1: no version information available (required by /mnt/SDCARD/System/lib/libpng16.so.16)
./2s2h.elf: /usr/lib/libz.so.1: no version information available (required by /mnt/SDCARD/System/lib/libpng16.so.16)
./2s2h.elf: symbol lookup error: /mnt/SDCARD/System/lib/libpng16.so.16: undefined symbol: inflateValidate, version ZLIB_1.2.9
Running in Fake Keyboard mode
Using ConfigFile soh2.gptk
Joystick 0 has game controller name 'Xbox 360 Controller'

**Comment by cizia64** [comment]
ship of harkinian requires to use the compatibility binary, however it's slow with it.
