### ISSUE TITLE
Hotkeys for Mupen64Plus standalone emulator stop working after updating the portmaster app

### ISSUE THREAD

**Issue by Dionstef** [cizia64/CrossMix-OS#216]
Hello,

After a lot of trial and error I discovered that the hotkeys for the Mupen64Plus standalone emulator stop working when I update the portmaster app to the latest version. I found a way to install an earlier version but it was a bin annoying.

**Comment by ja-keeler** [comment]
I have found this can be an issue with the gptokeysb2 file in the app/portmaster/portmaster folder I downloaded the file from the crossmix install and this resolved it for me

**Comment by Dionstef** [comment]
> I have found this can be an issue with the gptokeysb2 file in the app/portmaster/portmaster folder I downloaded the file from the crossmix install and this resolved it for me

It worked for me as well. Thanks!
