### ISSUE TITLE
Other psx cores

### ISSUE THREAD

**Issue by mrc04d** [cizia64/CrossMix-OS#22]
Have anyone got the other psx cores working?
Clean install and highlight a psx game and select any core other than the default just goes back to the game selection screen

**Comment by cobaltgit** [comment]
Oh? Duckstation and swanstation work out of the box for me, this is weird?

**Comment by sirchia** [comment]
@mrc04d its most likely a missing/misplaced bios. For the default the bios is optional, but the other two require it.
I also had this but after I added the missing bios files they work fine.

**Comment by cobaltgit** [comment]
Update: yeah you need bios files for duckstation/swanstation, PCSX ReARMed has hle bios emulation so it's optional

**Comment by cizia64** [comment]
Yes bios files are required for SwanStation/DuckStation. I close this one ;)
