### ISSUE TITLE
retroarch cheats doesn't load

### ISSUE THREAD

**Issue by mattitotti96** [cizia64/CrossMix-OS#23]
Hi I wanna use cheat on ps1 title but when I click the .cht file it immediately going out from the menu and the game immediately start and in the menu there are no list of cheats I put the .cht file in .retroarch/cheats/pcsxrearmed if you can help me I will do a donation

**Comment by cizia64** [comment]
Hi, normally you can browse cheat files from "Quick Menu -> Cheats -> Load Cheat File (Replace)".

If it resume the game directly when you try to load the .cht file it means that the file format is not right. You probably try to load native pcsx cheats (for PCSX standalone) and not libretro/retroarch cheat format. As you can see [here](https://docs.libretro.com/library/pcsx_rearmed/#features) native cheats are not supported by the libretro version of PCSX-Rearmed.

So you probably have to start with compatible cheats, for example [from here ](https://github.com/libretro/libretro-database/tree/master/cht/Sony%20-%20PlayStation). I have quickly tested with Scrable on Retroarch/PCSX-Rearmed and it works great.

Do not forget to click on "Apply Changes" or to enable "Apply After Toggle" just after making your changes.

**Comment by mattitotti96** [comment]
> Hi, normally you can browse cheat files from "Quick Menu -> Cheats -> Load Cheat File (Replace)".
> 
> If it resume the game directly when you try to load the .cht file it means that the file format is not right. You probably try to load native pcsx cheats (for PCSX standalone) and not libretro/retroarch cheat format. As you can see [here](https://docs.libretro.com/library/pcsx_rearmed/#features) native cheats are not supported by the libretro version of PCSX-Rearmed.
> 
> So you probably have to start with compatible cheats, for example [from here ](https://github.com/libretro/libretro-database/tree/master/cht/Sony%20-%20PlayStation). I have quickly tested with Scrable on Retroarch/PCSX-Rearmed and it works great.
> 
> Do not forget to click on "Apply Changes" or to enable "Apply After Toggle" just after making your changes.

yeah i use duckstation cheat and it doesn't support it.........i downloaded the cht by libretro but i'm italian and the majority of cheats doesn't work meanwile the duckstation database has all the type of version of cheats that are specificatly for each version ,i try to edit the file cht that i'm interested but it doesn't work

**Comment by cizia64** [comment]
Sorry I can't help more on this, the cheat files should work theoretically but duckstation core is poorly documented,  this problem should be addressed to general retroarch support
