### ISSUE TITLE
Xbox controller layout possible?

### ISSUE THREAD

**Issue by seriouz** [cizia64/CrossMix-OS#24]
I really like the Trimui Smart Pro but my problem is that I play/playing far too much hours Xbox where the face buttons have a different layout. The worst is the inversion of A and B.
Is it somehow possible, that I can remap at least the A and B buttons on the system level, so that I can use a Xbox layout on the Trimui Smart Pro, too?

![c19568c4-c7b8-4b5f-beec-6a7202778cba](https://github.com/cizia64/CrossMix-OS/assets/4722613/6dc2062f-e522-4994-9e4a-7fd37028c767)

**Comment by cizia64** [comment]
It's not (easily) possible in the main menu.
It's possible in retroarch menu (settings -> input -> Menu controls -> Menu Swap OK and Cancel Buttons)

**Comment by seriouz** [comment]
Thank you for the answer, this quick fix helps a little.
How is it possible on the main menu?
The best way would be to set it directly somewhere in the Linux distro. But I can't find where the controller is registered in Tina.

**Comment by cizia64** [comment]
I don't know how it can be done without editing the MainUI binary.

If you want to dig the subject : 
`trimui_inputd` binary is managing the input of the TSP.

To see what is happening on the input : 
`/mnt/SDCARD/System/usr/trimui/scripts/evtest    /dev/input/event3`

**Comment by cizia64** [comment]
So it's possible in retroarch but not in MainUI.
I close it as it's not possible to edit MainUI behavior without sources.

**Comment by cizia64** [comment]
Will be implemented in CrossMix v1.3.0 : https://github.com/cizia64/CrossMix-OS/pull/147

**Comment by seriouz** [comment]
@cizia64 I have the v1.4.0 but I don't see a setting anywhere to activate the button switch. Where is it located exactly?
