### ISSUE TITLE
crossmix os problem corrupted new san disk sd card

### ISSUE THREAD

**Issue by kaimeowkai** [cizia64/CrossMix-OS#243]
everything was working normally  but when i hit refresh roms then hit the scraper for ps roms all the roms disappeared from the ps folder within crossmix os. They were still visible within windows but the files were corrupted. the sd card now has bad sectors in that location. i have to get another card. it was only 1 day old RIP

**Comment by cizia64** [comment]
That's sad but if you have bad sectors it's more a hardware problem than something related to CrossMix.
