### ISSUE TITLE
[Quality of Life] Add wsdd2

### ISSUE THREAD

**Issue by V1t3r** [cizia64/CrossMix-OS#246]
WSD/LLMNR Discovery/Name Service Daemon.
What about to add wsdd2 binary to make Windows machines automaticaly detect trimui when you enable SMB? Just make addtional sh in Network or modify when you enable SMB

**Comment by V1t3r** [comment]
https://github.com/christgau/wsdd.git
tested this right on crossmix - works well - just maybe need to be integrated into menus

**Comment by Isa7q** [comment]
Isso seria interessante, não consigo conectar o tsp por smb pelo explore acabo usando um app de ftp

**Comment by cizia64** [comment]
Hi interesting !
I already added [avahi](https://github.com/cizia64/CrossMix-OS/blob/main/System/starts/%C2%B0post_starts.sh#L78C60-L78C65), so normally you can just type `\\tsp` or `\\tsp.local` in your file explorer address bar to access to SMB shares of the TSP.

However it's true that WS-Discovery makes things even easier.
I suggest to enable it when SMB is enabled with a command line like that : `wsdd --interface wlan0 -n TSP`

**Comment by cizia64** [comment]
https://github.com/cizia64/CrossMix-OS/pull/292
I finally choose a C++ implementation of the WS-Discovery protocol (less memory used) : https://github.com/gershnik/wsdd-native.
Thanks for pointing out this feature 👍🏻
