### ISSUE TITLE
Best section - shortcuts do not work

### ISSUE THREAD

**Issue by tom2199** [cizia64/CrossMix-OS#26]
I tried to use the shortcuts, but the roms do not launch. The shortcut looks like this:
`D:\Best\Bloons\Roms\PSPMINIS\Bloons TD (USA).txt`
Inside the txt is this:
`mnt/SDCARD/Roms/PSPMINIS/Bloons TD (USA).cso`
The game starts fine from the menu, but not from the Best section.

**Comment by cizia64** [comment]
May be the first slash is missing in 
```shell
/mnt/SDCARD/Roms/PSPMINIS/Bloons TD (USA).cso
```
?
