### ISSUE TITLE
[Feature request] Add citra emulator (3ds)

### ISSUE THREAD

**Issue by Garmii** [cizia64/CrossMix-OS#264]
Is it possible to add citra emulator to trimui sp. I've seen citra retroarch core, but looking at the code. I can not undersand how can be done. Anyways it could be possible due to hardware requirements?

**Comment by cobaltgit** [comment]
TSP is not powerful enough for 3DS emulation..

**Comment by Garmii** [comment]
Oh that's sad... Thanks for the info
