### ISSUE TITLE
[Feature Request] Disable standby during active networking

### ISSUE THREAD

**Issue by Asser82** [cizia64/CrossMix-OS#286]
As for the scraping process it would be helpful to disable auto standby, when networking over SMB/SSH is enabled. Otherwise the device goes into standby, which interrupts ongoing copy operations of large rom sets or port libraries.

**Comment by cizia64** [comment]
You talk about the integrated Scraper from CrossMix ? In this case it [will be OK](https://github.com/cizia64/CrossMix-OS/commit/68d614ce06ea09a5971ae0d50d52b3c7fb631ac6) for the next update 👍🏻.

**Comment by Asser82** [comment]
I have seen the change for the scraper, so I hoped it could be possible to turn off stand by during other long running operations, like during SMB enabled. Or maybe there could be a script set to turn standby on/off as desired by the user.

**Comment by cizia64** [comment]
SMB users don't necessarily want to prevent sleep mode, however you can easily disable sleep mode manually in "Settings -> Display -> Lock Screen Time".
You can also put [this flag](https://github.com/cizia64/CrossMix-OS/blob/main/System/usr/trimui/scripts/scraper/scrap_screenscraper.sh#L338)  : `echo 1 >/tmp/stay_awake`

**Comment by Asser82** [comment]
OK, did not find this setting previously. So nothing to do.
