### ISSUE TITLE
port chiaki or ps remote play?

### ISSUE THREAD

**Issue by rexeo-asia** [cizia64/CrossMix-OS#29]
Hi there, is it possible to port chiaki since moonlight streaming is supported?

**Comment by angelsky11** [comment]
+1

**Comment by cizia64** [comment]
This is a question for the community, feel free to ask on: 

- [TrimUI Reddit community](https://www.reddit.com/r/trimui/)
- [RGH](https://discord.com/invite/retro-game-handhelds-529983248114122762)  discord server
- [Retro handhelds](https://discord.com/invite/retrohandhelds) discord server
