### ISSUE TITLE
Stuck on USB storage screen

### ISSUE THREAD

**Issue by gheedsgreed** [cizia64/CrossMix-OS#310]
Just updated to 1.3.0 last night. Everything seemed to be working except my Retroarch hotkeys aren't working (haven't looked into yet). I used the USB storage feature to connect it to my PC. Afterwards, I ejected the device using Windows taskbar (as directed by Crossmix OS), and Pressed B to exit. Nothing happened, so I disconnected the USB cable and tried again with no success. Now it is still stuck on the "Press B to exit" screen. I've tried all the buttons with no success, including pressing B, holding B, pressing Power, holding Power, etc. Any way to reboot?

**Comment by gheedsgreed** [comment]
Okay, holding the Power button longer eventually turned off the device. I tried USB storage again and the same thing happened. Seems like pressing the B button does not reboot and the only option is hard shut down with the Power button.

**Comment by OLDMIKED** [comment]
This appears to be a known issue.  Go-to the 1.3.0 release page and scroll to the bottom

**Comment by cizia64** [comment]
This is fixe, just run OTA again to apply the hotfix
