### ISSUE TITLE
brightness shortcuts still won't work on 1.3 version

### ISSUE THREAD

**Issue by ChellyL** [cizia64/CrossMix-OS#311]
hi, i just update my tsp to the latest 1.3 version,  
but i tried some games found that the brightness shortcuts written in the wiki don't work
whether in a game or main ui , i press start + volume +/- but not the brightness only the volume changes
what could i do to fix this problem ?or it‘s still a bug ?

thank ! Merry Xmas !

**Comment by Nevrdid** [comment]
Brightness shortcut is star+L1/R1.

**Comment by ChellyL** [comment]
> Brightness shortcut is star+L1/R1.

oh thanks ! just realized that i used the wrong shortcuts, problem solved 👌
