### ISSUE TITLE
Warn users that updates wipe save files

### ISSUE THREAD

**Issue by slrgt** [cizia64/CrossMix-OS#33]
I updated to 1.1 and then realized that all my save files are gone. I thought this would just update everything and not erase my save files. Luckily I have an older backup of my save files but I think there should be a warning somewhere in the release notes 

EDIT: The save files aren't wiped for PPSSPP emulator, theyre are now two folders with the old version of the emulator and one with the new version of the emulator. You can copy paste the .config folder over to the new PPSSPP folder and keep all your progress

**Comment by cizia64** [comment]
Yes the updates doesn't wipe any save file (it will override cores configuration but as I spent a lot of time to tune it, it should be better to update them each time).
PPSSPP should require a migration script for the saves from the v1.0.0 (I will do that) but for the v1.1.0 you have to move it manually indeed.

**Comment by cizia64** [comment]
Migration script implemented in CrossMix v1.2.1
