### ISSUE TITLE
Feature Request: LEDS on only when battery is low

### ISSUE THREAD

**Issue by slrgt** [cizia64/CrossMix-OS#35]
Hi I like having the LEDs disabled but I would like the option to only enable the middle LED (not the joysticks) when battery is low (10%) as a warning so i know to charge my TSP

**Comment by diffequal** [comment]
You can edit the Battery level.sh file by setting all color values to 0 (lines 31-37) except for the last line. 

        100|9[0-9]) set_led_color 0 255 0 ;; # Green
        8[0-9]|7[0-9]) set_led_color 127 255 0 ;; # Chartreuse Green
        6[0-9]) set_led_color 255 255 0 ;; # Yellow
        5[0-9]) set_led_color 255 165 0 ;; # Orange
        4[0-9]) set_led_color 255 140 0 ;; # Dark Orange
        3[0-9]) set_led_color 255 69 0 ;; # Red Orange
        2[0-9]) set_led_color 255 20 0 ;; # Vermilion

**Comment by slrgt** [comment]
And this will enable the middle led to turn on only when theres low battery?

**Comment by diffequal** [comment]
All the LEDs will turn on.

**Comment by slrgt** [comment]
Is it possible to do it for only the middle led?

**Comment by diffequal** [comment]
No idea

**Comment by slrgt** [comment]
ok, where can i find batterylevel.sh?

**Comment by diffequal** [comment]
Apps\SystemTools\Menu\LEDS (value)

**Comment by slrgt** [comment]
Thanks this seems to work but once i go to the Best or Games section the leds turn on. Im guessing this is because of my theme? Where can i find the settings of my theme it from affecting the leds?

**Comment by cizia64** [comment]
In CrossMix v1.21, you have a script in System Tools to switch on in red the central led on low battery.
