### ISSUE TITLE
Syncthing login

### ISSUE THREAD

**Issue by michaelpequeno** [cizia64/CrossMix-OS#38]
Hello, I'm trying to use Syncthing and it's asking for a login. What would it be?

**Comment by cobaltgit** [comment]
The login for the syncthing server on the console should be in `/mnt/SDCARD/System/etc/syncthing/config.xml`

**Comment by cizia64** [comment]
Hi, if you have enabled Syncthing from System Tools app then it's indicated on it ;) 
https://github.com/cizia64/CrossMix-OS/blob/main/Apps/SystemTools/Menu/Imgs/NETWORK%23%23Syncthing%20(state).png
