### ISSUE TITLE
French translation sucks... Improvement proposal

### ISSUE THREAD

**Issue by dxdatabase** [cizia64/CrossMix-OS#39]
Hi, nice project ! But the french translation (from original firmware) is awfull... I join 2 lang files with better translation for french language. [](url)
[fr.lang.txt](https://github.com/user-attachments/files/15895953/fr.lang.txt)
[fr.lang.short.txt](https://github.com/user-attachments/files/15895954/fr.lang.short.txt)

**Comment by cizia64** [comment]
Good to know, I will apply this improvement on next release, thank you !

**Comment by cizia64** [comment]
Will be applied  in CrossMix v1.2.0 ;)
