### ISSUE TITLE
Recommend adding installation instructions

### ISSUE THREAD

**Issue by candre23** [cizia64/CrossMix-OS#4]
Even if instructions are just "uncompress with 7zip and copy everything to SD card", you should probably specify that process for people who really don't know what to do with the .7z file.  Perhaps include a note about backing up the factory files first, so if something goes wrong you don't get accused of "bricking" somebody's handheld.  I get that it seems pretty straightforward and obvious, but you need to bear in mind that for some users, this _is_ their first rodeo.

**Comment by cizia64** [comment]
Yes, it requires a full documentation. I will update the readme soon.
Users are also asking for a video any help will be welcome to help the community to discover how to install it.

**Comment by cizia64** [comment]
I have added few instructions for installation in the readme.

**Comment by cizia64** [comment]
Feel free to re-open if you think that some information is missing ;)
