### ISSUE TITLE
Heating up after minutes of gameplay even on "weak systems"

### ISSUE THREAD

**Issue by iuridias** [cizia64/CrossMix-OS#44]
Hello, greetings!
Firstly, congratulations on the excellent implementation you made. A thousand times better than stock OS. Sorry for the English, I'm Brazilian.

I've been testing it for about 5 days and so far everything works perfectly for me.
The only point I noticed is that the device is heating up after minutes of gameplay, even with weaker systems (like GBA, NES, etc.), and the battery is draining faster than normal (my device is less than 10 days old). After a while I discovered that FN was configured by default to boost the CPU, and I believe the key was activated. So I disabled it and just in case I changed the default function of the FN key, but I think it still remains the same. Normally in stock you wouldn't see this type of situation.

Could it be that for some reason it is accelerating the CPU even unnecessarily, and this is causing it to heat up and drain more battery power?

**Comment by cobaltgit** [comment]
You might want to edit the cpufreq.sh scripts for the emulators and tune the minimum and maximum CPU frequencies accordingly as well as the governor, that should help reduce temps a bit. There's a pull request with these configurations but it's not been merged yet, will be later down the line. Besides, this handheld naturally has poor thermals so it's nothing out of the ordinary.

**Comment by cizia64** [comment]
There's indeed a difference on the Fn key CPU management : 
- When disabled on stock, it always override the cpu speed to a low value. So even if you customize the cpu speed in the launch scripts the speed will be forced to low.
- On CrossMix, when Fn is disabled the speed is by default and is impacted by each customization in launch scripts.

We will make better tuning on CPU soon, I will give more info about this soon.

**Comment by iuridias** [comment]
Thanks guys for explanation. I'm looking forward to the next versions!
