### ISSUE TITLE
Retroarch Atari Lynx can't use zipped roms ?

### ISSUE THREAD

**Issue by dxdatabase** [cizia64/CrossMix-OS#45]
Zipped roms work fine with a lot of emulators (like GBA, SFC, N64...). But not with Atari Lynx : 

[INFO] [Content]: Core requires uncompressed content - extracting archive to temporary directory.
[ERROR] [Content]: Échec à l'extraction de contenu depuis le fichier compressé.: "/mnt/SDCARD/Emus/LYNX/../../Roms/LYNX/Electrocop (World).zip". (= can't extract)

I unzip the rom on the Trimui via an SSH shell to test if it's not corrupted, and it work fine and launch.

**Comment by cizia64** [comment]
Thanks for the feedback, it will be fixed in CrossMix v1.2.0 : https://github.com/cizia64/CrossMix-OS/commit/b7b94afa6f1ab7e52b2a5904f422395c2692ec15

**Comment by dxdatabase** [comment]
Still don't work with this new core... Not a big problem.

**Comment by diffequal** [comment]
> Still don't work with this new core... Not a big problem.

Maybe there is an issue with your roms, I checked with mine and zip files work fine, even with the older core.

**Comment by dxdatabase** [comment]
Very strange... My roms are ok :

```
file Electrocop\ \(World\).zip 
Electrocop (World).zip: Zip archive data, at least v2.0 to extract, compression method=deflate
zip -T Electrocop\ \(World\).zip 
test of Electrocop (World).zip OK
```

**Comment by cizia64** [comment]
Please test with CrossMix 1.2.1. Feel free to re-open if it's not solved.
