### ISSUE TITLE
CrossMix-OS

### ISSUE THREAD

**Issue by weroleg21** [cizia64/CrossMix-OS#46]
The only thing missing is the browser in the menu

**Comment by cizia64** [comment]
Hi, can you detail ? You mean a web browser ?

**Comment by cizia64** [comment]
This is a question for the community, feel free to ask on: 

- [TrimUI Reddit community](https://www.reddit.com/r/trimui/)
- [RGH](https://discord.com/invite/retro-game-handhelds-529983248114122762)  discord server
- [Retro handhelds](https://discord.com/invite/retrohandhelds) discord server
