### ISSUE TITLE
PPSSPP: can't choose between OpenGL and Vulkan backend

### ISSUE THREAD

**Issue by mg3600** [cizia64/CrossMix-OS#47]
I think it has something to do with the config.json file, because it has the OpenGL launch sh file in it as default launch. I can replace it with the Vulkan one, but it is tedious to always edit the config file on the computer. Another file "launch_1.15.4.sh" is also included in the PSP emu folder but it is the older version of PPSSPP and also does not let me change the backend inside the app.
I tried to replace the whole PSP emu folder with the stock OS's one, but then every PSP game disappeared on my Trimui altogether with the the whole PSP emulatior menu.

**Comment by welblade** [comment]
![image](https://github.com/cizia64/CrossMix-OS/assets/637273/8ae815b3-a132-4d42-aa9d-31a0e81ea8a9)
This line of code change the backend everytime you start the emulator, you can remove it and the config file will not change anymore.

**Comment by corngoblin** [comment]
If you go to your PSP games and hit X you can choose to boot the game in Vulkan or OpenGL and set what it defaults to.

**Comment by cizia64** [comment]
> This line of code change the backend everytime you start the emulator, you can remove it and the config file will not change anymore.

Please avoid to modify the launch scripts, use X button instead to change the default backend (this line is here for that!)

**Comment by mg3600** [comment]
Thank you all for your help! Pushing the X button was the solution to my problem, it was that simple :)

@cizia64 your system is amazing by the way, thank you for your hard work!
