### ISSUE TITLE
Menu button on the console brings up RetroArch setting instead of console menu

### ISSUE THREAD

**Issue by mg3600** [cizia64/CrossMix-OS#48]
I played around with retroarch settings and one of the tweaks, the behaviour of the menu button on the console (the button next to the bottom left corner of the screen) won't bring up the menu anymore, instead brings up the retroarch menu. It is annoying because it is not possible to load or save outside retroarch anymore.

**Comment by cobaltgit** [comment]
What emulator are you using? Since those cores using Vulkan bypasses the trimui middleman menu (whatever it's called)

**Comment by mg3600** [comment]
Changing back to gl did the trick, thank you very much. I would never have figured out that it matters.

For others seeking the answer: in retroarch menu > settings> video > output > video > should be on gl (not vulkan)
