### ISSUE TITLE
PS1 games don't resume from when powered off when powered back on

### ISSUE THREAD

**Issue by cobaltgit** [cizia64/CrossMix-OS#5]
When powering the system on after powering off while running a PS1 emulator, instead of loading from the save state that was meant to be created before powering off, the message `Failed to load state from "<game name>.state.auto"` appears and the emulation starts anew. I've tested this on only Crash Bandicoot so far using the PCSX ReARMed and SwanStation cores.

**Comment by cizia64** [comment]
Indeed. Thank you for the report !

**Comment by cizia64** [comment]
Will be fixed in next version.
 https://github.com/cizia64/CrossMix-OS/commit/ddc408a070db22f6bc1931e87a7aea5532f424ef.
