### ISSUE TITLE
Add Jellifyn, if possible.

### ISSUE THREAD

**Issue by meeeaCH** [cizia64/CrossMix-OS#52]
Hello, I would like to request to add Jellyfin to the system, if possible. It would be a nice addition.

Why Jellyfin:
- In my opinion, it runs better than Plex or Kodi. I use it on Fire Stick Lite and it runs fine.
- When I used Plex I had to have internet connection even, if I wanted to play the movies on local network. But, it could be me who messed up things and that's why it did not work without internet.
- It only needs an IP address to connect to the server, If you plan to stream your stuff locally you don't need a password to your profile, so its easy to connect.

**Comment by cizia64** [comment]
That's a good idea but I don't think that this binary has already been compiled for the TSP.
You should address this request on the community ([Reddit](https://www.reddit.com/r/trimui/) or RGH/Retro Handhelds discord).
If one day someone compile it, I will be happy to include it in CrossMix ;)

**Comment by meeeaCH** [comment]
I thought about it a bit more and we don't even need the Jellyfin client, a media player which supports UPNp/DLNA is enough. And it would work with Plex, Jellyfin or other apps. 

I tried to figure out how to cross compile VLC, but I got lost. I'll just post a request.

**Comment by Nevrdid** [comment]
A solution is to use jellyfin_mpv_shim. It can be installed with pip3 however the actuall pip install is broken as it miss ssl library i believe. 
The app is just a cast client for jellyfin using mpv which is already installed.

**Comment by meeeaCH** [comment]
I see, so it would function as a Chromecast or Amazon Fire Stick for example. It's a good option, but it would be nice to be able to browse the movie libraries.

I'll check it out tomorrow. But I can't promise anything.

**Comment by Nevrdid** [comment]
I'm actually building nfs-utils as my jellyfin library is also shared as a nfs server. I'll honestly just browse and start anything like that. No more need for a jellyfin client once that will be setup x')

**Comment by cizia64** [comment]
This is a question for the community, feel free to ask on: 

- [TrimUI Reddit community](https://www.reddit.com/r/trimui/)
- [RGH](https://discord.com/invite/retro-game-handhelds-529983248114122762)  discord server
- [Retro handhelds](https://discord.com/invite/retrohandhelds) discord server
