### ISSUE TITLE
n64 not working anymore

### ISSUE THREAD

**Issue by leocvf** [cizia64/CrossMix-OS#6]
I tried both RetroArch emulators, but the games won't launch

**Comment by cizia64** [comment]
It has been reported as OK for some users. There is a problem somewhere on your install, did you start with a fresh SD carad ?

**Comment by leocvf** [comment]
I did start from a fresh SD, I going to try another brand maybe the sd is faulty

**Comment by cizia64** [comment]
OK let me know what will be the result :)

**Comment by leocvf** [comment]
It seems like it is working for some games, the default core is ParaLLEl N64, Mupen is not working, the default emulator is paraLLEI N64 using gln64, kirby64 don't work right with this settings, if you use cache_interpreter you can use glide64 but the performance is bad

**Comment by leocvf** [comment]
Solved, not all emulation options work but the default one is working
