### ISSUE TITLE
N64 testing document

### ISSUE THREAD

**Issue by 2Bane** [cizia64/CrossMix-OS#62]
https://docs.google.com/spreadsheets/d/19Q8hlohoAv1tmU7egPgluUMTvC9Bn1ypywFfA8kh9n4/edit?gid=0#gid=0

Finished additional testing of N64 NTSC library.

Best all around configuration. I found to be Mupen/Dynarec. (Cizia mentioned that Mupen/Pure configuration in 1.1.0 was an error.)

Second best was ParaLLEl with Rice GFX plugin closely followed by ParaLLEl with Gln64 (Which is a bit slower in some cases but looks better imo.)

Mupen/Pure_Interpreter is a fallback for certain games that crash otherwise.

Is it possible to have .sh that can launch these cores but substitute a secondary config file? Image for example.

![image](https://github.com/cizia64/CrossMix-OS/assets/153442102/8ac76df2-8242-470e-88a0-8102fe27bec4)

**Comment by 2Bane** [comment]
Havent had much time to test, i'll probably wait until Rob-on-linux feels the port is good to go before doing more.

Early stuff I've been trying it is a marked improvement over RA Cores. Some of the harder games that crash outright are playable enough on it.

**Comment by cobaltgit** [comment]
I'm not sure if rob-retro-linux is going to develop the standalone mupen64plus any further..

**Comment by josegonzalez** [comment]
New version of mupen64plus was released like a week after the last post. Would be cool to see if that release (2.6.0) improves performance over the release in Crossmix (2.5.9). Not sure how to compile it for the Smart Pro though :(

**Comment by cobaltgit** [comment]
I've managed to compile 2.6.0 from source and test it, had to add a few libs and rendering is mostly glitched no matter the video plugin, might be to do with my config but I'm totally unsure
