### ISSUE TITLE
3DO and Pico-8 "empty" 

### ISSUE THREAD

**Issue by thiago-123456** [cizia64/CrossMix-OS#7]
Hi, I'm having an issue with 3DO an Pico-8 games.

3DO:
I have some files on 3DO directory, but they are not appearing for me. 
Also tried saving them on Panasonic folder, but luck either.
Files are .CHD

Pico-8
Same behavior with .p8 files

For both, refreshing does not help.

Any ideas?

Thanks!

**Comment by cizia64** [comment]
For Pico-8 the rom folder is "PICO" (it's case sensitive), (I really hesitated with "PICO8"). I've just tested it should work correctly.

For 3DO there is a bug in TrimUI MainUI software : Roms folder beginning with a number are not detected :D  I will fix that, you can rename Roms/3DO folder into Roms/PANASONIC and modify the path in the config.json too.

**Comment by cobaltgit** [comment]
Could also rename it to Opera, since that's the name of the emulator and Panasonic weren't the only OEM of 3DO consoles.

**Comment by cizia64** [comment]
I don't want to name the emu folders by the emulator name but by platform name. I choose PANASONIC because I saw that in Miyoo Mini Onion. But if it is also the codename yes we could (I have pushed my update before seeing your message).  
https://github.com/cizia64/CrossMix-OS/commit/1f451f586e071134c0c87c35dc5de925fa82a665
We will choose the best, some other opinions ?

**Comment by cobaltgit** [comment]
Sounds good to me, the first OEM people think of when 3DO springs to mind is Panasonic anyway as well as the R.E.A.L logo

**Comment by thiago-123456** [comment]
I moved the files to PICO and after refreshing the rooms folowed with a restart solved the problem.

I saved the 3DO games to PANASONIC folder and changed \Emus\3DO\config.json acordingly. 

Works now... 

3DO emulation is a bit choppy, with sound clipping. I'll try to change the emulator settings and see what heppens.

Thanks for the amazing job!

**Comment by cobaltgit** [comment]
Yeah the 3DO is a bit harder to emulate for the Smart Pro..

**Comment by cizia64** [comment]
3DO and PICO-8 wrapper have been fixed / Improved in the v1.1.0 of CrossMix-OS
PICO-8: https://github.com/cizia64/CrossMix-OS/commit/7d5fc4b30a1c5fb696e2d130eebebaad37e06b32
3DO: https://github.com/cizia64/CrossMix-OS/commit/1f451f586e071134c0c87c35dc5de925fa82a665
