### ISSUE TITLE
Emulators not showing if using sub folders due to emucleaner

### ISSUE THREAD

**Issue by damo08** [cizia64/CrossMix-OS#73]
If I have my roms in the correct folders but in organised sub folders, emucleaner won't show the emulator unless there is one rom in the root of the folder.

Stock os didn't have this issue.

**Comment by cizia64** [comment]
Thanks for the feedback, will be fixed in v1.2.0  https://github.com/cizia64/CrossMix-OS/commit/481fd35f01fcd6a58bd9d960ee372d585a804013

**Comment by cizia64** [comment]
Fixed in CrossMix v1.2.1.
