### ISSUE TITLE
New french traduction for the next V1.2.0 update 

### ISSUE THREAD

**Issue by gabrielpsp** [cizia64/CrossMix-OS#83]
Hello,

Here's another quick revision of the French translation.
[CrossMix Os French language V2.zip](https://github.com/user-attachments/files/16155797/CrossMix.Os.French.language.V2.zip)
 Thank you

**Comment by cizia64** [comment]
It's already updated for the v1.2.0 : https://github.com/cizia64/CrossMix-OS/blob/main/trimui/res/lang/fr.lang
Is it much improved ?

**Comment by dxdatabase** [comment]
It's better, but both translation need to change "0":	"Jeux", to "0":	"Émulateurs" to be perfect and match new english translation :)

**Comment by gabrielpsp** [comment]
I've improved some words and synthax, and yes @dxdatabase is right :)

**Comment by gabrielpsp** [comment]
Fixed :) I use the words "0":"Consoles" which is a best mix between 'Jeux' and 'Emulateurs'.
[CrossMix Os French Language V2.1.zip](https://github.com/user-attachments/files/16173195/CrossMix.Os.French.Language.V2.1.zip)

**Comment by dxdatabase** [comment]
In my "Jeux" tab, I've CPC 6128. It's not a "Console" 😉

**Comment by cizia64** [comment]
Published in CrossMix v1.2.1.
