### ISSUE TITLE
Insert Coin

### ISSUE THREAD

**Issue by AndMas79** [cizia64/CrossMix-OS#84]
In some roms the select button as coin doesn't work... do you know how to make it work?

**Comment by AndMas79** [comment]
> Will be fixed in crossmix v1.2.0. For now either bind coin to a different button or set `input_hotkey_block_delay` in retroarch.cfg to something like 180.

Thanks for the information, I'll try to do as you say

**Comment by gabrielpsp** [comment]
Do you have an approximate launch window for V1.2.0?

**Comment by cizia64** [comment]
Fixed in CrossMix v1.2.1
