### ISSUE TITLE
Save location scheme

### ISSUE THREAD

**Issue by joaopedrosgs** [cizia64/CrossMix-OS#98]
It would be nice to be able to set the save location as it normally is (RetroArch\.retroarch\saves) instead of RetroArch\.retroarch\saves\**RomFolderName**\**Corename**)

This would allow me to share saves between my EmuDeck installation and the trimui.

**Comment by cizia64** [comment]
Hi, it's a bad choice from EmuDeck to have all the saves in the same folder I will not reproduce this choice in CrossMix sorry ;)

**Comment by joaopedrosgs** [comment]
to be honest, now that I've looked into the issue, I agree with you
