### ISSUE TITLE
Portmaster does not open

### ISSUE THREAD

**Issue by roo1234** [cizia64/CrossMix-OS#99]
I have installed Crossmix 110 this week and updated to 120 today. Never ran Portmaster before, and now it displays the loading screen and just closes in some seconds. WIFI is connected. Everything else seems normal, including the great scraping app.
Tks

**Comment by cizia64** [comment]
Hi, Try to remove SDCARD/System/bin/python3 and reboot

**Comment by roo1234** [comment]
It worked. After removing the file, Portmaster was installed the next reboot and ran OK.
